
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for automatically logging the macro breakdown and estimated carbon footprint of meals.
 *
 * - autoLogMacros - A function that takes a meal photo and description and returns the macro breakdown and carbon footprint.
 * - AutoLogMacrosInput - The input type for the autoLogMacros function.
 * - AutoLogMacrosOutput - The return type for the autoLogMacros function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutoLogMacrosInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the meal, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  description: z.string().describe('A description of the meal.'),
});
export type AutoLogMacrosInput = z.infer<typeof AutoLogMacrosInputSchema>;

const AutoLogMacrosOutputSchema = z.object({
  carbohydrates: z
    .number()
    .describe('The estimated amount of carbohydrates in grams.'),
  fats: z.number().describe('The estimated amount of fats in grams.'),
  proteins: z.number().describe('The estimated amount of proteins in grams.'),
  carbonFootprintEstimate: z.number().describe('Estimated carbon footprint of the meal in kg CO2 equivalent (CO2e). Provide a general estimate based on common ingredients if precise data is unavailable.')
});
export type AutoLogMacrosOutput = z.infer<typeof AutoLogMacrosOutputSchema>;

export async function autoLogMacros(input: AutoLogMacrosInput): Promise<AutoLogMacrosOutput> {
  return autoLogMacrosFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autoLogMacrosPrompt',
  input: {schema: AutoLogMacrosInputSchema},
  output: {schema: AutoLogMacrosOutputSchema},
  prompt: `You are a nutritional expert. You will analyze the provided information about a meal and estimate its macro breakdown (carbohydrates, fats, and proteins) in grams AND its estimated carbon footprint in kg CO2 equivalent (CO2e).

Description of the meal: {{{description}}}
Photo of the meal: {{media url=photoDataUri}}

For carbon footprint, consider common ingredients and their general environmental impact. If specific data is unavailable, provide a reasonable estimate based on typical food categories (e.g., red meat vs. vegetables).

Please provide your best estimate for the following:
- Carbohydrates (grams):
- Fats (grams):
- Proteins (grams):
- Carbon Footprint (kg CO2e):`,
});

const autoLogMacrosFlow = ai.defineFlow(
  {
    name: 'autoLogMacrosFlow',
    inputSchema: AutoLogMacrosInputSchema,
    outputSchema: AutoLogMacrosOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
     if (!output) {
      throw new Error("AI analysis did not return an output for macros and carbon footprint.");
    }
    return output;
  }
);
